name: Build

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  Build-x86:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Platform=x86 /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
  Build-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Platform=x64 /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
